name: Deploy YouTube Plugin

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install Packages
        run: npm install
      - name: Build page
        run: |
          unset CI
          export GENERATE_SOURCEMAP=false
          npm run build
      - uses: appleboy/scp-action@master
        with:
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: "ffcs"
          key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          port: 22
          source: "./build"
          target: "/home/ubuntu/youtube-plugin"
